### ISSUE TITLE
Debian several problems

### ISSUE THREAD

**Issue by spijker** [vFense/vFenseAgent-nix#14]
I installed the agent on several different debian systems ( squeeze , wheezy ) , and they all failed with these error messages.
Even in a clean docker like environment it failes.
Are there minimal requirements packages voor debian ? 

The log is starting with ,
Moved daemon to init.d
Added daemon to startup.
Checking run levels.
Done checking run levels.
Attempting to start agent.
TopPatch Agent is running.
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1259, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

DEBUG : 05/01/2014 10:06:40 AM : Added result / bf40daee-df64-4659-aa82-6dd8a0f47c7f-agent to OpQueue.
INFO : 05/01/2014 10:06:40 AM : Ready up.
DEBUG : 05/01/2014 10:06:44 AM : bf40daee-df64-4659-aa82-6dd8a0f47c7f-agent / result will not be saved.
DEBUG : 05/01/2014 10:06:44 AM : Results to be sent: [<serveroperation.sofoperation.ResultOperation instance at 0x2e04170>]
DEBUG : 05/01/2014 10:06:44 AM : Operation has not been processed, or unknown operation was received.

ERROR : 05/01/2014 09:53:32 AM : Unable to save vine password.
ERROR : 05/01/2014 09:53:32 AM : Exception: [Errno 8] Exec format error
DEBUG : 05/01/2014 09:53:32 AM : Traceback (most recent call last):
  File "/opt/TopPatch/agent/plugins/ra/vine/**init**.py", line 198, in _vine_set_password
    stderr=subprocess.PIPE
  File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1259, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error

DEBUG : 05/01/2014 09:53:33 AM : Unable to import module rv.rvsofoperation. Skipping.
ERROR : 05/01/2014 09:53:33 AM : Exception: **init**() takes exactly 12 arguments (1 given)
DEBUG : 05/01/2014 09:53:33 AM : Traceback (most recent call last):
  File "/opt/TopPatch/agent/src/core.py", line 103, in load_plugins
    plug = _class()
TypeError: __init__() takes exactly 12 arguments (1 given)

INFO : 05/01/2014 09:53:33 AM : Starting agent.
DEBUG : 05/01/2014 09:53:33 AM : Internet connection detected.
INFO : 05/01/2014 09:53:33 AM : Sending initial data.
INFO : 05/01/2014 09:53:33 AM : Process the following operation: {'core_data': {}, 'reboot_delay_seconds': 90, 'plugin': u'', 'type': u'new_agent', 'raw_result': '', 'raw_operation': '{"operation_id": "d500cf8b-38bd-49ad-a10c-d2
b088c502d9-agent", "operation": "new_agent", "plugin": ""}', 'json_message': {u'operation_id': u'd500cf8b-38bd-49ad-a10c-d2b088c502d9-agent', u'operation': u'new_agent', u'plugin': u''}, 'request_method': '', 'urn_response': '',
 'error': '', 'data': [], 'id': u'd500cf8b-38bd-49ad-a10c-d2b088c502d9-agent', 'shutdown_delay_seconds': 90, 'plugin_data': {}}
DEBUG : 05/01/2014 09:53:33 AM : Adding operation d500cf8b-38bd-49ad-a10c-d2b088c502d9-agent.
DEBUG : 05/01/2014 09:53:33 AM : System info sent: {"os_code": "linux", "version": "3.11.0-19-generic", "bit_type": "64", "host_name": "", "computer_name": "5790666c679b", "os_string": "debian 7.4"}
ERROR : 05/01/2014 09:53:33 AM : Error while processing operation: {'core_data': {'system_info': {'os_code': 'linux', 'version': '3.11.0-19-generic', 'bit_type': '64', 'host_name': '', 'computer_name': '5790666c679b', 'os_string
': 'debian 7.4'}}, 'reboot_delay_seconds': 90, 'plugin': u'', 'type': u'new_agent', 'raw_result': '', 'raw_operation': '{"operation_id": "d500cf8b-38bd-49ad-a10c-d2b088c502d9-agent", "operation": "new_agent", "plugin": ""}', 'js
on_message': {u'operation_id': u'd500cf8b-38bd-49ad-a10c-d2b088c502d9-agent', u'operation': u'new_agent', u'plugin': u''}, 'request_method': '', 'urn_response': '', 'error': '', 'data': [], 'id': u'd500cf8b-38bd-49ad-a10c-d2b088
c502d9-agent', 'shutdown_delay_seconds': 90, 'plugin_data': {}}
ERROR : 05/01/2014 09:53:33 AM : Exception: [Errno 2] No such file or directory
DEBUG : 05/01/2014 09:53:33 AM : Traceback (most recent call last):
  File "/opt/TopPatch/agent/src/serveroperation/operationmanager.py", line 139, in process_operation
    operation_methods[operation.type](operation)
  File "/opt/TopPatch/agent/src/serveroperation/operationmanager.py", line 167, in new_agent_op
    operation = self._initial_data(operation)
  File "/opt/TopPatch/agent/src/serveroperation/operationmanager.py", line 280, in _initial_data
    operation.core_data[OperationValue.HardwareInfo] = self.hardware_info()
  File "/opt/TopPatch/agent/src/serveroperation/operationmanager.py", line 596, in hardware_info
    hardware_info = systeminfo.hardware()
  File "/opt/TopPatch/agent/src/utils/systeminfo.py", line 116, in hardware
    return utils.hardware.get_hw_info()
  File "/opt/TopPatch/agent/src/utils/hardware.py", line 22, in get_hw_info
    hw_info['display'] = DisplayInfo().get_display_list()
  File "/opt/TopPatch/agent/src/utils/hardware.py", line 309, in get_display_list
    raw_output = self._get_pci_device_info()
  File "/opt/TopPatch/agent/src/utils/hardware.py", line 236, in _get_pci_device_info
    process = subprocess.Popen(cmd, stdout=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1259, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

ERROR : 05/01/2014 09:54:34 AM : Unable to read data from server. Invalid JSON?
ERROR : 05/01/2014 09:54:34 AM : Exception: No JSON object could be decoded
DEBUG : 05/01/2014 09:54:34 AM : Traceback (most recent call last):
  File "/opt/TopPatch/agent/src/net/netmanager.py", line 176, in send_message
    received_data = response.json()
  File "/opt/TopPatch/agent/deps/requests/models.py", line 651, in json
    return json.loads(self.text or self.content, **kwargs)
  File "/usr/lib/python2.7/json/**init**.py", line 326, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by spijker** [comment]
fixed, missing package ;)

**Comment by linuxdynasty** [comment]
What was the missing package? So we can document it, thank you.

**Comment by spijker** [comment]
Sorry, still finding out ,
made a diff between two systems one working one not.
I will post it when found.

**Comment by spijker** [comment]
So let's close this one ;) , The agent was running in openvz environment, there was no pciutils package installed for lspci, Installed the package (apt-get install pciutils ), no hardware output, but a fully working agent !
