### ISSUE TITLE
Updates failed due to user input. 

### ISSUE THREAD

**Issue by arukaen** [vFense/vFenseAgent-nix#16]
This is the error that was returned in vFense operations tab.

Checking for services that may need to be restarted...done.
Checking for services that may need to be restarted...done.
Checking init scripts...
Failed to open terminal.debconf: whiptail output the above errors, giving up!
dpkg: error processing libssl1.0.0:armhf (--configure):
 subprocess installed post-installation script returned error exit status 255
Errors were encountered while processing:
 libssl1.0.0:armhf
E: Sub-process /usr/bin/dpkg returned an error code (1)

![selection_002](https://cloud.githubusercontent.com/assets/3124395/3067960/a2920bb0-e288-11e3-934f-a09de604d722.png)

I tried to install the package manually and this user input popped up. 

![selection_001](https://cloud.githubusercontent.com/assets/3124395/3067936/6965866e-e288-11e3-988e-9bb58ce9024b.png)

**Comment by hchac** [comment]
Hey there arukaen, did you pass the '-y' option to apt-get when you tried to install it manually?

**Comment by arukaen** [comment]
@humchacon I did not.

**Comment by hchac** [comment]
From the looks of the error message it seems the '-y' (what the agent uses) option passes the user input section, but then there was a failure at install time.

Are these packages still available to install for you?

**Comment by arukaen** [comment]
No they arent not. Ended up running apt-get after manually.
