### ISSUE TITLE
Github source significantly different than agent download?

### ISSUE THREAD

**Issue by jlk** [vFense/vFenseAgent-nix#8]
Folks - I ran into an issue during agent install where serverport is not being passed to the validate method. Was going to patch and submit a pull request, but github source looks way different than content of VFAgent_0_7_0-rpm6_64.tar.gz - what gives?

**Comment by hchac** [comment]
The current branches on github have been updated with changes that will be pushed out to agent v0.7.1. I will be making sure, after v0.7.1 release, that the master branch keeps current with the latest download available on our website.

Also, the agent downloads are "builds" created for each platform, and therefore only the dependencies for that platform are included. The "build" also moves some files around, like the agent_utils, and avoids including the devtools directory.

**Comment by jlk** [comment]
Figured something like that. :) Can you add the build scripts into the github repo?

A lot easier to troubleshoot things when I can reproduce things fully.

Also - is the agent being packaged into deb/rpm yet? if not I’ll work on the spec file for rpm.

John

**Comment by hchac** [comment]
The agents current build script is written in Go, it can be seen in "devtools/forge.go". I am planning to re-write it in python so that it is more in tune with the project.

The nix-agent is not currently being packaged into a deb/rpm, although we plan to shortly. The rpm spec file would be appreciated.

**Comment by hchac** [comment]
The build script has been re-written in python: https://github.com/toppatch/vFenseAgent-nix/blob/development/agent/devtools/build_agent
